// Generated by CoffeeScript 1.6.2
var Animal, Cavalo, Cobra, cavalo, cobra, _ref, _ref1,
__hasProp = {}.hasOwnProperty,
__extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Animal = (function() {
  function Animal(nome) {
    this.nome = nome;
  }

  Animal.prototype.mover = function(metros) {
    return console.log(this.nome + (" se moveu " + metros + " metros."));
  };

  return Animal;

})();

Cobra = (function(_super) {
  __extends(Cobra, _super);

  function Cobra() {
    _ref = Cobra.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Cobra.prototype.mover = function() {
    console.log("Rastejando...");
    return Cobra.__super__.mover.call(this, 5);
  };

  return Cobra;

})(Animal);

Cavalo = (function(_super) {
  __extends(Cavalo, _super);

  function Cavalo() {
    _ref1 = Cavalo.__super__.constructor.apply(this, arguments);
    return _ref1;
  }

  Cavalo.prototype.mover = function() {
    console.log("Galopando...");
    return Cavalo.__super__.mover.call(this, 45);
  };

  return Cavalo;

})(Animal);

cobra = new Cobra("A cobra");

cavalo = new Cavalo("O cavalo");

cobra.mover();

cavalo.mover();
