// Generated by CoffeeScript 1.6.2
var Calculadora;

window.Calculadora = Calculadora = (function() {
  function Calculadora() {}

  Calculadora.prototype.somar = function(a, b) {
    return a + b;
  };

  Calculadora.prototype.subtrair = function(a, b) {
    return a - b;
  };

  Calculadora.prototype.dividir = function(a, b) {
    return a / b;
  };

  Calculadora.prototype.multiplicar = function(a, b) {
    return a * b;
  };

  return Calculadora;

})();
